
export const openAPIAllowlist = [
  "get-site-id",
  "revokeAccessToken",
  "getAccountBuildStatus",
  "listMembersForAccount",
  "addMemberToAccount",
  "listSitesForAccount",
  "createSiteInTeam",
  "listAccountsForUser",
  "createAccount",
  "getAccount",
  "updateAccount",
  "cancelAccount",
  "listAccountAuditEvents",
  "enableAnalytics",
  "disableAnalytics",
  // "listSiteAssets",
  // "createSiteAsset",
  // "getSiteAssetInfo",
  // "updateSiteAsset",
  // "deleteSiteAsset",
  // "getSiteAssetPublicSignature",
  "listPaymentMethodsForUser",
  "listSiteBuildHooks",
  "createSiteBuildHook",
  "getSiteBuildHook",
  "updateSiteBuildHook",
  // "deleteSiteBuildHook",
  "getSiteBuild",
  "listSiteBuilds",
  "createSiteBuild",
  "updateSiteBuildLog",
  "notifyBuildStart",
  "listDeployKeys",
  "createDeployKey",
  "getDeployKey",
  // "deleteDeployKey",
  "listSiteDeploys",
  "createSiteDeploy",
  "getDeploy",
  // "deleteDeploy",
  "getSiteDeploy",
  // "deleteSiteDeploy",
  "updateSiteDeploy",
  "restoreSiteDeploy",
  "lockDeploy",
  "unlockDeploy",
  "cancelSiteDeploy",
  "getSimplePublicDeploy",
  // "listSiteDevServerHooks",
  // "createSiteDevServerHook",
  // "getSiteDevServerHook",
  // "updateSiteDevServerHook",
  // "deleteSiteDevServerHook",

  // Will add back once we've properly tested
  // "getDnsRecords",
  // "createDnsRecord",
  // "getIndividualDnsRecord",
  // "deleteDnsRecord",
  // "getDnsZones",
  // "createDnsZone",
  // "getDnsZone",
  // "deleteDnsZone",
  // "enableDnsZoneIpv6",
  // "transferDnsZone",
  // "getDNSForSite",
  // "configureDNSForSite",
  "getEnvVars",
  "createEnvVars",
  "getSiteEnvVars",
  "getEnvVar",
  "updateEnvVar",
  "setEnvVarValue",
  "deleteEnvVar",
  "deleteEnvVarValue",
  "listSiteFiles or listDeployFiles",
  "getSiteFileByPathName",
  "listSiteForms",
  "getSiteForm",
  "deleteSiteForm",
  // "uploadDeployFunction",
  "listHooksBySiteId",
  "createHookBySiteId",
  "getHook",
  "updateHook",
  "deleteHook",
  "listHookTypes",
  "enableHook",
  "getSiteMetadata",
  "updateSiteMetadata",
  // "showTicket",
  // "createTicket",
  // "authorizeWithTicket",
  // "exchangeTicket",
  // "getOrganizationReceipts",
  // "getOrganizationReceipt",
  "listOrganizationsForUser",
  "getOrganization",
  // "updateOrganization",
  // "createOrganizationLogo",
  // "deleteOrganizationLogo",
  // "getOrganizationAccounts",
  // "getOrganizationInvoices",
  // "getOrganizationInvoice",
  // "getOrganizationClientToken",
  // "createOrganizationPayment",
  // "updateOrganizationSamlSettings",
  "listSites",
  "createSite",
  "getSite",
  "updateSite",
  // for now let's require UI for deleting sites
  // "deleteSite",
  "listSiteDeployedBranches",
  "rollbackSiteDeploy",
  "unlinkSiteRepo",
  // "getSimplePublicSite",
  "listSiteSnippets",
  "createSiteSnippet",
  "getSiteSnippet",
  "deleteSiteSnippet",
  "updateSiteSnippet",
  // "showSiteTLSCertificate",
  // "provisionSiteTLSCertificate",
  // "getAllCertificates",
  "listFormSubmissions",
  "listSiteSubmissions",
  "listFormSubmission",
  "deleteSubmission",
  "getCurrentUser"
];
