plugins {
    id 'com.android.library'
}

android {
    namespace 'com.example.portal.core'
    compileSdk 35

    defaultConfig {
        minSdk 23
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.13.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    testImplementation 'junit:junit:4.13.2'
}
